# Generated by Django 2.0.6 on 2018-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('gtin', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Vendor code')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('price', models.IntegerField(blank=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
