# Generated by Django 2.0.6 on 2018-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
