# Generated by Django 2.0.6 on 2018-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emma', '0002_auto_20180728_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created at'),
        ),
    ]
