# Generated by Django 2.0.6 on 2018-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emma', '0004_auto_20180731_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='retail_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
